// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftSync.DAL.Data;

#nullable disable

namespace SoftSync.DAL.Migrations
{
    [DbContext(typeof(SoftSyncDbContext))]
    [Migration("20260707161937_InitData")]
    partial class InitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("CaseStudies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Scenario = "Thành viên nhóm của bạn không đóng góp. Bạn sẽ làm gì?",
                            SkillId = 2,
                            Title = "Group Communication"
                        },
                        new
                        {
                            Id = 2,
                            Scenario = "Bạn nhận ra rằng bạn sẽ trễ hạn vào ngày mai. Hành động đầu tiên của bạn là gì?",
                            SkillId = 1,
                            Title = "Missed Deadline"
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudyOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseStudyId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseStudyId");

                    b.ToTable("CaseStudyOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseStudyId = 1,
                            Feedback = "Điều này dẫn đến kiệt sức và không giải quyết được vấn đề động lực nhóm.",
                            IsRecommended = false,
                            OptionText = "Làm công việc của họ."
                        },
                        new
                        {
                            Id = 2,
                            CaseStudyId = 1,
                            Feedback = "Giao tiếp trực tiếp và đồng cảm là chìa khóa.",
                            IsRecommended = true,
                            OptionText = "Nói chuyện riêng với họ để hiểu tình hình."
                        },
                        new
                        {
                            Id = 3,
                            CaseStudyId = 2,
                            Feedback = "Rủi ro và không quản lý được kỳ vọng.",
                            IsRecommended = false,
                            OptionText = "Làm việc cả đêm và hy vọng điều tốt nhất."
                        },
                        new
                        {
                            Id = 4,
                            CaseStudyId = 2,
                            Feedback = "Minh bạch và lập kế hoạch chủ động là điều cần thiết.",
                            IsRecommended = true,
                            OptionText = "Thông báo ngay cho các bên liên quan và đề xuất một lịch trình mới."
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntryTestQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntryTestQuestionId");

                    b.ToTable("EntryTestOptions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("EntryTestQuestions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunicationLevel")
                        .HasColumnType("int");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticalThinkingLevel")
                        .HasColumnType("int");

                    b.Property<int>("CriticalThinkingScore")
                        .HasColumnType("int");

                    b.Property<int>("OverallLevel")
                        .HasColumnType("int");

                    b.Property<int>("TimeManagementLevel")
                        .HasColumnType("int");

                    b.Property<int>("TimeManagementScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EntryTestResults");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortBio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mentors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://i.pravatar.cc/150?u=katherine",
                            Expertise = "Leadership & Soft Skills",
                            Name = "Dr. Katherine",
                            ShortBio = "15 years of experience in corporate training."
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://i.pravatar.cc/150?u=john",
                            Expertise = "Problem Solving",
                            Name = "John Smith",
                            ShortBio = "Former Google engineer, expert in algorithms and thinking."
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsPerRound")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("MiniGames");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniGameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiniGameId");

                    b.HasIndex("UserId");

                    b.ToTable("MiniGameAttempts");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniGameQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiniGameQuestionId");

                    b.ToTable("MiniGameOptions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniGameId")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiniGameId");

                    b.ToTable("MiniGameQuestions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PercentComplete")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.RoadmapItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RoadmapItems");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản lý thời gian hiệu quả.",
                            IconName = "bi-clock",
                            Name = "Time Management"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giao tiếp hiệu quả.",
                            IconName = "bi-chat-dots",
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tư duy phản biện.",
                            IconName = "bi-lightbulb",
                            Name = "Critical Thinking"
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.TheoryLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("TheoryLessons");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            CreatedAt = new DateTime(2026, 6, 27, 16, 19, 37, 619, DateTimeKind.Utc).AddTicks(1343),
                            Email = "demo@softsync.vn",
                            FullName = "Nguyễn Văn A",
                            Goal = "Cải thiện kỹ năng giao tiếp",
                            PasswordHash = "100000.dWcqqpmE7DUu0BDsGm6a/Q==.ulFl+DO1KnWnHf34E3bKOZrUc0WH20FhnAcu+Mqzqeg=",
                            Role = 0
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.UserSkillSelection", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkillSelections");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentResult", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudy", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany("CaseStudies")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudyOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.CaseStudy", "CaseStudy")
                        .WithMany("Options")
                        .HasForeignKey("CaseStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStudy");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ChatMessage", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.EntryTestQuestion", "EntryTestQuestion")
                        .WithMany("Options")
                        .HasForeignKey("EntryTestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryTestQuestion");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestQuestion", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestResult", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGame", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameAttempt", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.MiniGame", "MiniGame")
                        .WithMany()
                        .HasForeignKey("MiniGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.MiniGameQuestion", "MiniGameQuestion")
                        .WithMany("Options")
                        .HasForeignKey("MiniGameQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniGameQuestion");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameQuestion", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.MiniGame", "MiniGame")
                        .WithMany("Questions")
                        .HasForeignKey("MiniGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniGame");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ProgressLog", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.RoadmapItem", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("RoadmapItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.TheoryLesson", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.UserSkillSelection", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("SkillSelections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudy", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGame", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.Skill", b =>
                {
                    b.Navigation("CaseStudies");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.User", b =>
                {
                    b.Navigation("AssessmentResults");

                    b.Navigation("ChatMessages");

                    b.Navigation("ProgressLogs");

                    b.Navigation("RoadmapItems");

                    b.Navigation("SkillSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
