// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftSync.DAL.Data;

#nullable disable

namespace SoftSync.DAL.Migrations
{
    [DbContext(typeof(SoftSyncDbContext))]
    partial class SoftSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AssessmentOptions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("CaseStudies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Scenario = "Your team member is not contributing. What do you do?",
                            SkillId = 1,
                            Title = "Group Communication"
                        },
                        new
                        {
                            Id = 2,
                            Scenario = "You realize you will miss a deadline tomorrow. What is your first action?",
                            SkillId = 3,
                            Title = "Missed Deadline"
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudyOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseStudyId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseStudyId");

                    b.ToTable("CaseStudyOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseStudyId = 1,
                            Feedback = "This leads to burnout and doesn't solve the team dynamic issue.",
                            IsRecommended = false,
                            OptionText = "Do their work myself."
                        },
                        new
                        {
                            Id = 2,
                            CaseStudyId = 1,
                            Feedback = "Direct, empathetic communication is key.",
                            IsRecommended = true,
                            OptionText = "Talk to them privately to understand their situation."
                        },
                        new
                        {
                            Id = 3,
                            CaseStudyId = 2,
                            Feedback = "Risky and doesn't manage expectations.",
                            IsRecommended = false,
                            OptionText = "Work all night and hope for the best."
                        },
                        new
                        {
                            Id = 4,
                            CaseStudyId = 2,
                            Feedback = "Transparency and proactive planning are essential.",
                            IsRecommended = true,
                            OptionText = "Inform the stakeholders immediately and propose a new timeline."
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntryTestQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntryTestQuestionId");

                    b.ToTable("EntryTestOptions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("EntryTestQuestions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunicationLevel")
                        .HasColumnType("int");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticalThinkingLevel")
                        .HasColumnType("int");

                    b.Property<int>("CriticalThinkingScore")
                        .HasColumnType("int");

                    b.Property<int>("OverallLevel")
                        .HasColumnType("int");

                    b.Property<int>("TimeManagementLevel")
                        .HasColumnType("int");

                    b.Property<int>("TimeManagementScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EntryTestResults");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortBio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mentors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://i.pravatar.cc/150?u=katherine",
                            Expertise = "Leadership & Soft Skills",
                            Name = "Dr. Katherine",
                            ShortBio = "15 years of experience in corporate training."
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://i.pravatar.cc/150?u=john",
                            Expertise = "Problem Solving",
                            Name = "John Smith",
                            ShortBio = "Former Google engineer, expert in algorithms and thinking."
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsPerRound")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("MiniGames");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniGameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiniGameId");

                    b.HasIndex("UserId");

                    b.ToTable("MiniGameAttempts");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniGameQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiniGameQuestionId");

                    b.ToTable("MiniGameOptions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MiniGameId")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiniGameId");

                    b.ToTable("MiniGameQuestions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ProgressLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PercentComplete")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.RoadmapItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RoadmapItems");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Effective verbal and non-verbal interaction.",
                            IconName = "bi-chat-dots",
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Collaborating effectively with others.",
                            IconName = "bi-people",
                            Name = "Teamwork"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Organizing and planning your time.",
                            IconName = "bi-clock",
                            Name = "Time Management"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Analyzing info to make judgments.",
                            IconName = "bi-lightbulb",
                            Name = "Critical Thinking"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Finding solutions to complex issues.",
                            IconName = "bi-tools",
                            Name = "Problem Solving"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Recognizing and managing emotions.",
                            IconName = "bi-heart",
                            Name = "Emotional Management"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Adjusting to new conditions.",
                            IconName = "bi-arrow-repeat",
                            Name = "Adaptability"
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.TheoryLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("TheoryLessons");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            CreatedAt = new DateTime(2026, 6, 26, 22, 11, 6, 719, DateTimeKind.Utc).AddTicks(5166),
                            Email = "demo@softsync.vn",
                            FullName = "Nguyễn Văn A",
                            Goal = "Cải thiện kỹ năng giao tiếp",
                            PasswordHash = "100000.ia/YzWCIvvslvI9U5YNlkg==.LdOq2bhddth5faKFocvX+9T/WOo7V+7fYTpN8CuAZnk=",
                            Role = 0
                        });
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.UserSkillSelection", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkillSelections");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.AssessmentQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany("Questions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentResult", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudy", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany("CaseStudies")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudyOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.CaseStudy", "CaseStudy")
                        .WithMany("Options")
                        .HasForeignKey("CaseStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStudy");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ChatMessage", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.EntryTestQuestion", "EntryTestQuestion")
                        .WithMany("Options")
                        .HasForeignKey("EntryTestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryTestQuestion");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestQuestion", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestResult", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGame", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameAttempt", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.MiniGame", "MiniGame")
                        .WithMany()
                        .HasForeignKey("MiniGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameOption", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.MiniGameQuestion", "MiniGameQuestion")
                        .WithMany("Options")
                        .HasForeignKey("MiniGameQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniGameQuestion");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameQuestion", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.MiniGame", "MiniGame")
                        .WithMany("Questions")
                        .HasForeignKey("MiniGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniGame");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.ProgressLog", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.RoadmapItem", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("RoadmapItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.TheoryLesson", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.UserSkillSelection", b =>
                {
                    b.HasOne("SoftSync.DAL.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftSync.DAL.Entities.User", "User")
                        .WithMany("SkillSelections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.AssessmentQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.CaseStudy", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.EntryTestQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGame", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.MiniGameQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.Skill", b =>
                {
                    b.Navigation("CaseStudies");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SoftSync.DAL.Entities.User", b =>
                {
                    b.Navigation("AssessmentResults");

                    b.Navigation("ChatMessages");

                    b.Navigation("ProgressLogs");

                    b.Navigation("RoadmapItems");

                    b.Navigation("SkillSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
